// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBQnDWXUKQU-0NrO_u2gGpDoXkuZQ0h5s',
    appId: '1:630453007440:web:1cbea460e5db8dc8cecd55',
    messagingSenderId: '630453007440',
    projectId: 'ai-learn-db',
    authDomain: 'ai-learn-db.firebaseapp.com',
    storageBucket: 'ai-learn-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMOZo7YBC1IDIwVL6GDliBv6BH5HF5_kI',
    appId: '1:630453007440:android:b7fbab7d03f7a0dfcecd55',
    messagingSenderId: '630453007440',
    projectId: 'ai-learn-db',
    storageBucket: 'ai-learn-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVSonG-tLT3QCL3YJJVKNFTep0uGnsx2w',
    appId: '1:630453007440:ios:fd75208622b9de87cecd55',
    messagingSenderId: '630453007440',
    projectId: 'ai-learn-db',
    storageBucket: 'ai-learn-db.firebasestorage.app',
    iosBundleId: 'com.example.hybridlms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVSonG-tLT3QCL3YJJVKNFTep0uGnsx2w',
    appId: '1:630453007440:ios:fd75208622b9de87cecd55',
    messagingSenderId: '630453007440',
    projectId: 'ai-learn-db',
    storageBucket: 'ai-learn-db.firebasestorage.app',
    iosBundleId: 'com.example.hybridlms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBQnDWXUKQU-0NrO_u2gGpDoXkuZQ0h5s',
    appId: '1:630453007440:web:7e08553623ffc9d1cecd55',
    messagingSenderId: '630453007440',
    projectId: 'ai-learn-db',
    authDomain: 'ai-learn-db.firebaseapp.com',
    storageBucket: 'ai-learn-db.firebasestorage.app',
  );

}